### ISSUE TITLE
GHC 8.6 support

### ISSUE THREAD

**Issue by simonmichael** [joelburget/easytest#12]
easytest doesn't build with GHC 8.6:
```
[2 of 4] Compiling EasyTest.Generators ( src/EasyTest/Generators.hs, .stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/EasyTest/Generators.o )

/Users/simon/src/DEVTOOLS/easytest/src/EasyTest/Generators.hs:110:3: error:
    • No instance for (Control.Monad.Fail.MonadFail Test)
        arising from a do statement
        with the failable pattern ‘Just a’
    • In a stmt of a 'do' block: Just a <- pure (ind i)
```
https://github.com/haskell/fgl/pull/80/commits/344a7e452630ace0f5c647e525e0299d99de5902 might be the kind of fix needed (I tried a bit but didn't get it working).

**Comment by joelburget** [comment]
Thanks for the heads-up. I haven't used 8.6 yet but I'll work on this today or tomorrow.

**Comment by simonmichael** [comment]
It’s not super urgent. I disabled our tests on appveyor for now. Thanks!

**Comment by felixonmars** [comment]
As a temporary workaround, adding `{-# language NoMonadFailDesugaring #-}` in src/EasyTest/Generators.hs helps here.

**Comment by peti** [comment]
This issue prevents us from building hledger for NixOS with ghc-8.6.1. :slightly_frowning_face:

**Comment by peti** [comment]
https://github.com/joelburget/easytest/pull/13 fixes this issue.

**Comment by peti** [comment]
Will you release a new version to Hackage?

**Comment by gwils** [comment]
As a hackage trustee, I have revised versions 0.1.1 and 0.2 so that they will not attempt to build on GHC 8.6.
This will prevent bad install plans for now, and releasing a new version would help too (by giving good install plans)

**Comment by peti** [comment]
@simonmichael, considering that `easytest` is the main reason blocking the entire `hledger` ecosystem from supporting ghc-8.6.1, maybe it's a good idea to use a different library for writing tests? I mean, there's no shortage of packages out there that offer plenty of nice features and that are very well maintained.

**Comment by simonmichael** [comment]
Thanks!
